apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: training/gateway:v1
        ports:
        - containerPort: 3001
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 1536Mi
              cpu: 55m
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3001
          initialDelaySeconds: 3
          failureThreshold: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3001
          initialDelaySeconds: 3
          failureThreshold: 3
          periodSeconds: 3
